version: "3.5"
services:
    ajudaime_webserver:
      build: phpdocker/nginx
      container_name: ajudaime-web
      working_dir: /application
      volumes:
          - ./:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./certs:/etc/nginx/certs
      ports:
        - "8888:8888"
        - "443:443"
        - "8088:8088"
      networks:
        - ajudaime-net

    ajudaime_php:
      build: phpdocker/php-fpm
      container_name: ajudaime-php
      working_dir: /application
      environment:
        XDEBUG_CONFIG: remote_host=192.168.15.4 #your docker network ip.
        PHP_IDE_CONFIG: "serverName=tolocalhost.com" #phpstorm need a environment var that tell who xdebug connect we must to listen.
      volumes:
        - ./:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - /tmp:/tmp
      networks:
        - ajudaime-net

networks:
  ajudaime-net:
    external:
      name: ajudaime_network